#!/bin/bash

VERSION=${1:-4.0.6}
OUT=${2:-out}

function check_exists() {
	local version="${1:-${VERSION}}"
	local dist="${2:-${OUT}/${version}.tar.gz}"

	[ -f "${dist}" ]
}

function download() {
	local version="${1:-${VERSION}}"
	local dist="${2:-${OUT}/${version}.tar.gz}"

	mkdir -p "$(dirname ${dist})"

	local url="https://dlcdn.apache.org/cassandra/${VERSION}/apache-cassandra-${VERSION}-bin.tar.gz"

	curl -Lo "${dist}" "${url}"
}

function extract() {
	local target_name="${1}"
	local filename="${2:-${OUT}/${VERSION}.tar.gz}"

	[ -d "${target_name}" ] && {
		return 0
	}

	[ -f "$filename" ] || {
		echo "No ${filename} archive found" >&2
		return 1
	}

	local out=$(dirname ${target_name})

	local new_head_dir=$(basename ${target_name})
	local head_dir_in_tar='[^/]\+'

	tar -xf "${filename}" --transform "s,${head_dir_in_tar},${new_head_dir}," -C "${out}"
}

function change_yaml_value() {
	local filename="${1}"
	local key="${2}"
	local new_value="${3}"

	[ -f "$filename" ] || {
		echo "Unable to open '${filename}'" >&2
		return 1
	}

	[ -n "$key" ] || {
		echo "Key cannot be empty" >&2
		return 1
	}

	sed -i "/${key}/s,:.*,: ${new_value}," "$filename"
}

function configure() {
	local dirname="${1}"
	local order="${2}"

	[ -z "${order}" ] && {
		echo "No order of the node is set" >&2
		return 1
	}

	[ -d "${dirname}" ] || {
		echo "No '${dirname}' directory exist" >&2
		return 1
	}

	local cassandra_yaml="${dirname}/conf/cassandra.yaml" 
	[ -f "${cassandra_yaml}" ] || {
		echo "No '${cassandra_yaml}' file exists. Is it a Cassandra distribution?" >&2
		return 1
	}

	local cassandra_env="${dirname}/conf/cassandra-env.sh" 
	[ -f "${cassandra_env}" ] || {
		echo "No '${cassandra_env}' file exists. Is it a Cassandra distribution?" >&2
		return 1
	}

	local jmx_port=$((27200 + order))
	sed -i "/^JMX_PORT=/s,=.*,=${jmx_port}," "${cassandra_env}"

	local storage_port=$((17000 + order))
	local native_transport_port=$((19040 + order))

	change_yaml_value "${cassandra_yaml}" '^storage_port' "${storage_port}"
	change_yaml_value "${cassandra_yaml}" '^ssl_storage_port' "${storage_port}"
	change_yaml_value "${cassandra_yaml}" '^native_transport_port' "${native_transport_port}"
	change_yaml_value "${cassandra_yaml}" '^\s*- seeds: ' '127.0.0.1:17001'
}

function setup() {
	local total_nodes="${1}"
	local node_dir_prefix="${2:-${OUT}/node}"

	local i=0
	while [ "$i" -lt "${total_nodes}" ]; do
		i=$((i + 1))

		local node_name="${node_dir_prefix}-${i}"

		extract "${node_name}"
		configure "${node_name}" "${i}"
	done
}


function get_log_file() {
	local node_name="${1}"


	local log_dir="${node_name}/logs"
	mkdir -p "${log_dir}"

	local log_file="${log_dir}/system.log"
	[ -f "$log_file" ] || touch "${log_file}"

	echo "${log_file}"
}

function start_cluster() {
	local total_nodes="${1}"
	local node_dir_prefix="${2:-${OUT}/node}"

	local seed_node="${node_dir_prefix}-1"
	[ -d "${seed_node}" ] || {
		echo "No '${seed_node}' seed node directory found."
		return 1
	}

	nodes_logs=()

	local log_file="$(get_log_file ${seed_node})"
	nodes+=("${log_file}")

	${seed_node}/bin/cassandra >/dev/null
	echo "Waiting for the seed node to start..."
	sleep 10

	echo "Starting nodes of the ring"
	local i=1
	while [ "$i" -lt "${total_nodes}" ]; do
		i=$((i + 1))

		local node_name="${node_dir_prefix}-${i}"

		local log_file="$(get_log_file ${node_name})"
		nodes+=("${log_file}")

		${node_name}/bin/cassandra >/dev/null

		sleep 10
	done

	echo "Waiting for nodes to start..."
	sleep 10
	tail -f ${nodes[*]}
}

check_exists "${VERSION}" ||
       	download "${VERSION}" &&
	setup 4 &&
	start_cluster 4 &&
       	echo "Success" || echo "Failure"
